### ISSUE TITLE
Error with version 1.2.0

### ISSUE THREAD

**Issue by Anto007** [NuruddinKhoiry/blastMining#3]
Hi @NuruddinKhoiry I pip installed blastMining v1.2.0 as per your suggestion and tried running Method A but it still gives me an error (possibly related to taxonkit flag?). Below are the command-lines I used and the error I got. I have also attached below the input file that I had used. Thank you very much in advance for your help here.

```
blastMining --version
blastMining v.1.2.0
blastMining vote -i newforBLASTmining_10_test_zotus_coverage_blastn_maxtarget10_screenresults.txt -o vote_method -e 0.001 -txl 99,97,95,90,85,80,75 -n 10 -sm test_zotus -j 100 -p vote_method -kp
Error: unknown shorthand flag: 'P' in -P
Usage:
  taxonkit reformat [flags]

Flags:
  -d, --delimiter string               field delimiter in input lineage (default ";")
  -F, --fill-miss-rank                 fill missing rank with original lineage information (experimental)
  -f, --format string                  output format, placeholders of rank are needed (default "{k};{p};{c};{o};{f};{g};{s}")
  -h, --help                           help for reformat
  -i, --lineage-field int              field index of lineage. data should be tab-separated (default 2)
  -r, --miss-rank-repl string          replacement string for missing rank, if given "", "unclassified xxx xxx" will used, where "unclassified " is settable by flag -p/--miss-rank-repl-prefix
  -p, --miss-rank-repl-prefix string   prefix for estimated taxon level (default "unclassified ")
  -R, --miss-taxid-repl string         replacement string for missing taxid
  -t, --show-lineage-taxids            show corresponding taxids of reformated lineage

Global Flags:
      --data-dir string   directory containing nodes.dmp and names.dmp (default "/home/jubin/.taxonkit")
      --line-buffered     use line buffering on output, i.e., immediately writing to stdin/file for every line of output
  -o, --out-file string   out file ("-" for stdout, suffix .gz for gzipped out) (default "-")
  -j, --threads int       number of CPUs. (default value: 1 for single-CPU PC, 2 for others) (default 2)
      --verbose           print verbose information

unknown shorthand flag: 'P' in -P
[ERRO] empty file: -
Traceback (most recent call last):
  File "/home/jubin/tools/conda_env_for_blastmining/bin/blastMining", line 8, in <module>
    sys.exit(main())
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/blastMining/blastMining.py", line 65, in main
    args.func(args)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/blastMining/vote/vote.py", line 85, in main
    tax = pd.read_csv(str('./'+os.path.join(args.outdir, "TMPDIR")+"/TAXONKIT.out"), sep='\t', header=None, dtype=str)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/jubin/tools/conda_env_for_blastmining/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```
Here's the input file I had used
[newforBLASTmining_10_test_zotus_coverage_blastn_maxtarget10_screenresults.txt](https://github.com/NuruddinKhoiry/blastMining/files/10299753/newforBLASTmining_10_test_zotus_coverage_blastn_maxtarget10_screenresults.txt)

**Comment by Anto007** [comment]
I managed to fix this issue by updating the taxonkit dependency at my end to the latest version. Everything seems perfect now; thanks!
